export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED' 

export const PURCASE_BURGER_START = 'PURCASE_BURGER_START' 
export const PURCASE_BURGER_SUCCESS = 'PURCASE_BURGER_SUCCESS' 
export const PURCASE_BURGER_FAIL = 'PURCASE_BURGER_FAIL' 
export const PURCASE_INIT = 'PURCASE_INIT' 

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START' 
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS' 
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL' 